zivid/zivid-cpp-samples

- Zivid/CMakeLists.txt
- ZividPCL/CMakeLists.txt
- Version requirement removed.
- Copying dependencies made universal.
- This file can now be used with Visual Studio and QT creator.
> CMakeLists file updated

- .clang-format
- .gitignore
- Downsample/Downsample.cpp
- Zivid/CaptureHDRCompleteSettings/CaptureHDRCompleteSettings.cpp
- Zivid/CaptureHDRLoop/CaptureHDRLoop.cpp
- Zivid/CaptureSavePLY/CaptureSavePLY.cpp
- Zivid/ConnectToSerialNumberCamera/ConnectToSerialNumberCamera.cpp
- Zivid/GetCameraIntrinsics/GetCameraIntrinsics.cpp
- Zivid/ReadZDF/ReadZDF.cpp
- Zivid/ZDF2PLY/ZDF2PLY.cpp
- ZividPCL/CaptureFromFileWritePCLVis3D/CaptureFromFileWritePCLVis3D.cpp
- ZividPCL/CaptureWritePCLVis3D/CaptureWritePCLVis3D.cpp
- ZividPCL/ReadPCLVis3D/ReadPCLVis3D.cpp
- ZividPCL/ZDF2PCD/ZDF2PCD.cpp
This is the first step for enabling CI on this repository (See #3).
I think it makes sense to merge this PR separately even if the full CI setup is not complete, to make sure we use proper formatting sooner rather than later. This will avoid adding even more code with inconsistent formatting until the CI setup is complete.
> Use clang format

- azure-pipelines.yml
- continuous-integration/linux/lint.sh
- continuous-integration/linux/platform-dependent/ubuntu-18.04/setup.sh
- continuous-integration/linux/setup.sh
This enables CI Azure Pipelines. It currently only checks code formatting, more checks will be added in the future. If a PR fails, merging will be blocked.
Here's [an example of it failing CI](https://dev.azure.com/zivid-devops/cpp-extra-samples/_build/results?buildId=212) after I intentionally broke formatting in a cpp file.
Fixes #3
> Lint in ci

- README.md
- ZividOpenCV/CMakeLists.txt
- ZividOpenCV/ZDF2OpenCV/ZDF2OpenCV.cpp
The sample imports a ZDF point cloud and converts it to OpenCV format.
> Add OpenCV sample

- CMakeLists.txt
- README.md
- ZividOpenCV/CaptureUndistortRGB/CaptureUndistortRGB.cpp
The sample undistorts an RGB image from a ZDF point cloud using Zivid camera intrinsics.
> Add OpenCV CaptureUndistortRGB sample

- CMakeLists.txt
- README.md
- continuous-integration/linux/platform-dependent/ubuntu-18.04/setup.sh
> Upgrade to Zivid 1.6

- azure-pipelines.yml
- continuous-integration/linux/build.sh
- continuous-integration/linux/platform-dependent/ubuntu-16.04/setup.sh
There's unfortunately a bug in Zivid which causes issues on Clang 3. An
internal issue has been logged for this.
> Add CI for Ubuntu 16.04

- CMakeLists.txt
Make OpenCV components non-optional, and add a missing OpenCV dependency.
> Opencv dependencies

- source/Applications/Advanced/HandEyeCalibration/PoseConversions/PoseConversions.cpp
While reviewing the python variant of this example, we found that we should only focus on Zivid related conversions. In addition I want the examples to read very similar between languages, as long as it doesn't compromise good code.
> Focus only on conversions relevant to Zivid

- source/Camera/Basic/CaptureTutorial.md
Make capture tutorial consistent between different repos / programming languages
> Update Capture Tutorial

- README.md
- source/CMakeLists.txt
- source/Camera/InfoUtilOther/FirmwareUpdater/FirmwareUpdater.cpp
This sample shows how to use the APIs to check whether a camera requires an updated, and update if required.
> Add sample for firmware update

- source/CMakeLists.txt
- source/Camera/InfoUtilOther/ZividBenchmark/ZividBenchmark.cpp
This is to be a public version for benchmarking Zivid performance.
This is how the output looks like: [benchmarkZivid.txt](https://github.com/zivid/cpp-extra-samples/files/4383281/benchmarkZivid.txt)
> Add Zivid Benchmark

- source/Camera/InfoUtilOther/ZividBenchmark/ZividBenchmark.cpp
This adds the training phase of capture assistant (suggest settings).
> Add assisted capture to ZividBenchmark

- .clang-format
- .clang-tidy
- README.md
- azure-pipelines.yml
- continuous-integration/linux/build.sh
- continuous-integration/linux/lint.sh
- continuous-integration/linux/platform-dependent/ubuntu-20.04/setup.sh
- source/Applications/Advanced/CaptureUndistortRGB/CaptureUndistortRGB.cpp
- source/Applications/Advanced/Downsample/Downsample.cpp
- source/Applications/Advanced/HandEyeCalibration/HandEyeCalibration/HandEyeCalibration.cpp
- source/Applications/Advanced/HandEyeCalibration/PoseConversions/PoseConversions.cpp
- source/Applications/Advanced/HandEyeCalibration/UtilizeEyeInHandCalibration/UtilizeEyeInHandCalibration.cpp
- source/Camera/Basic/Capture/Capture.cpp
- source/Camera/Basic/Capture2D/Capture2D.cpp
- source/Camera/Basic/CaptureAssistant/CaptureAssistant.cpp
- source/Camera/Basic/CaptureFromFile/CaptureFromFile.cpp
- source/Camera/InfoUtilOther/ZividBenchmark/ZividBenchmark.cpp
This PR also includes a commit to enable build on all samples!
This closes #17, closes #43, and closes #96
> Clang tidy on all samples

- source/CMakeLists.txt
> Stop copying Qt plugins folder

- source/Applications/Advanced/CreateDepthMap/CreateDepthMap.cpp
- source/CMakeLists.txt
This should have been done earlier. That is why this commit also modifies where the file is read from. See commit c700d8e.
> Add CreateDepthMap sample to CMakeLists

- README.md
> Update tutorial link in README

- continuous-integration/linux/platform-dependent/ubuntu-16.04/setup.sh
- continuous-integration/linux/platform-dependent/ubuntu-18.04/setup.sh
- continuous-integration/linux/platform-dependent/ubuntu-20.04/setup.sh
> Update CI to the official 2.0 SDK

- source/Camera/InfoUtilOther/ZividBenchmark/ZividBenchmark.cpp
> Print test headers in ZividBenchmark.cpp

- source/Applications/Advanced/CreateDepthMap/CreateDepthMap.cpp
Jet colormap is replaced by Viridis because it gives a better perception of depth.
Fixes #138
> Improve depth map visualization in CreateDepthMap.cpp

- README.md
- continuous-integration/linux/platform-dependent/ubuntu-16.04/setup.sh
- continuous-integration/linux/platform-dependent/ubuntu-18.04/setup.sh
- continuous-integration/linux/platform-dependent/ubuntu-20.04/setup.sh
- source/Applications/Advanced/Downsample/Downsample.cpp
- source/Applications/PointCloudTutorial.md
- source/CMakeLists.txt
Almost zero code to write. Deleted a lot of code and changed a couple of lines to match built-in function
> Update to Zivid SDK v2.1.0 and modify downsample sample

- continuous-integration/linux/platform-dependent/ubuntu-16.04/setup.sh
- continuous-integration/linux/platform-dependent/ubuntu-18.04/setup.sh
- continuous-integration/linux/platform-dependent/ubuntu-20.04/setup.sh
- source/CMakeLists.txt
PR to update samples to Zivid 2.2.0. 
**Before this can be merged to master:**
> Update to Zivid SDK 2.2.0

- README.md
- source/Applications/Advanced/MaskPointCloud/MaskPointCloud.cpp
- source/CMakeLists.txt
Created sample mask_point_cloud. 
Using cv::Mat as mask and iterating to copy within the mask. 
Storing result as pcl for easy visualization. 
Reused code from CreateDepthMap.cpp for depthmap viz
> Mask point cloud

- README.md
- source/Applications/Advanced/TransformPointCloudViaArucoMarker/TransformPointCloudViaArucoMarker.cpp
- source/CMakeLists.txt
The sample reads a point cloud, detects an aruco marker, and estimates
its pose. Then, it transforms the point cloud to the marker coordinate
frame and saves the transformed point cloud.
Continuation of https://github.com/zivid/zivid-cpp-samples/pull/153
> Add TransformPointCloudViaArucoMarker sample

- README.md
- source/CMakeLists.txt
- source/Camera/InfoUtilOther/PrintVersionInfo/PrintVersionInfo.cpp
List connected cameras and print version information.
> Add sample to list connected cameras

- README.md
- source/CMakeLists.txt
- source/Camera/InfoUtilOther/SettingsInfo/SettingsInfo.cpp
> Add SettingsInfo sample

- .clang-tidy
- README.md
- continuous-integration/linux/platform-dependent/ubuntu-18.04/setup.sh
- continuous-integration/linux/platform-dependent/ubuntu-20.04/setup.sh
- source/Applications/Advanced/ROIBoxViaArucoMarker/ROIBoxViaArucoMarker.cpp
- source/Applications/Advanced/ROIBoxViaCheckerboard/ROIBoxViaCheckerboard.cpp
- source/Applications/Advanced/TransformPointCloudViaArucoMarker/TransformPointCloudViaArucoMarker.cpp
- source/Applications/Advanced/TransformPointCloudViaCheckerboard/TransformPointCloudViaCheckerboard.cpp
- source/Applications/Basic/Visualization/CaptureFromFileCameraVis3D/CaptureFromFileCameraVis3D.cpp
- source/Applications/PointCloudTutorial.md
- source/CMakeLists.txt
- source/Camera/Basic/CaptureAssistant/CaptureAssistant.cpp
- source/Camera/Basic/CaptureFromFileCamera/CaptureFromFileCamera.cpp
- source/Camera/Basic/CaptureHDRCompleteSettings/CaptureHDRCompleteSettings.cpp
- source/Camera/Basic/CaptureTutorial.md
- source/Camera/Basic/QuickCaptureTutorial.md
Remember to do the following:
1. Ensure that modified/deleted/new files are correct
2. Make this commit message relevant for the changes
3. Force push
4. Delete branch after PR is merged
If this commit is an update from one SDK version to another,
make sure to create a release tag for previous version.
> Samples: Automatic updates to public repository

- source/Camera/InfoUtilOther/GetCameraIntrinsics/GetCameraIntrinsics.cpp
This commit fixes some bugs with some of the public samples
> Samples: Bug fixes
