zivid/zivid-cpp-samples

- ZividOpenCV/ZDF2OpenCV/ZDF2OpenCV.cpp
Clang gave me this error:
explicit template specialization cannot have a storage class
It can be fixed by just removing `static` from the specializations, but
I don't understand why any of these were declared static in the first
place, so let's just remove it entirely.
> Don't use internal linkage for function templates

- CMakeLists.txt
Don't look for packages if we're not using them
Moving `find_package` inside `if(USE...)` makes sure we don't call them
if we're not using them.
I'm still keeping them as optional though (not adding `REQUIRED`), so
that we can also print our own error message informing the user that
they have the option to turn the dependency off.
Also fixed some indentation problems
> Cmake fixups

- azure-pipelines.yml
- continuous-integration/linux/build.sh
- continuous-integration/linux/platform-dependent/ubuntu-18.04/setup.sh
- continuous-integration/linux/test.sh
I'm currently only building a subset of the samples which was easy to
get to build. Still, this will ensure those samples build, that cmake
works etc. Then we can expand with the OpenCV and Eigen samples later.
> Add building of samples in CI

- ZividOpenCV/CaptureUndistortRGB/CaptureUndistortRGB.cpp
If you run the original code in debug mode you will get an assertion failure. 
`CV_DbgAssert((unsigned)(i1 * DataType<_Tp>::channels) < (unsigned)(size.p[1] * channels()));`
This is because as the Mat::Mat constructor documentation puts it:
> size – 2D array size: Size(cols, rows) . In the Size() constructor, the number of rows and the number of columns go in the reverse order.
> Size() constructor inverted row column

- README.md
- ZividOpenCV/CaptureUndistortRGB/CaptureUndistortRGB.cpp
The last two commits represent two alternative approaches to a combined example.
fe39a35: Use #define to select whether to use 2D or 3D APIs
9698d44: Use std::getline() to prompt user to select 2D or 3D (actual implementation defaults to 3D after 5 seconds.
> Add 2D API to CaptureUndistortRGB example

- cmake/CompilerOptions.cmake
We convert and compare between signed and unsigned values a lot in these
samples, would complicate them too much to manually cast each time.
> Ignore some warnings

- continuous-integration/linux/build.sh
- continuous-integration/linux/lint.sh
`build.sh` used to build in the directory `/source/build` relative to the
repo root. Now we instead build in `/build` relative to the repo root.
This was the intention all along, the previous was just a bug.
`lint.sh` used to look for files in the entire repo. It now only looks in
the `source` folder, in order to avoid finding generated files in the
`build` folder.
This fixes #65
> CI: Use correct source and build dirs

- continuous-integration/linux/lint.sh
Fixes #75
Example when an error is found now:
```
(...)
/home/knatten/code/cpp-extra-samples/source/Camera/Basic/Capture/Capture.cpp
ok
/home/knatten/code/cpp-extra-samples/source/Camera/Basic/Capture2D/Capture2D.cpp
ok
/home/knatten/code/cpp-extra-samples/source/Camera/InfoUtilOther/GetCameraIntrinsics/GetCameraIntrinsics.cpp
17,18c17
<     
<             std::cout << "Connecting to the camera" << std::endl;
---
>         std::cout << "Connecting to the camera" << std::endl;
/home/knatten/code/cpp-extra-samples/source/Camera/InfoUtilOther/CameraUserData/CameraUserData.cpp
ok
ERROR: 1 formatting error(s) found! See the diffs for each file printed above.
```
I'm sure this could be improved even further, but this hopefully at least makes the situation better for now.
> More useful error message for clang-format errors

- README.md
- source/CMakeLists.txt
Fixes #74 
The correct version is 4.1.0. actually (not 4.0.1. or 4.1.1)
KB is fixed: https://zivid.atlassian.net/wiki/spaces/ZividKB/pages/61472793
> Fix OpenCV version

- README.md
- source/Applications/Advanced/CaptureUndistortRGB/CaptureUndistortRGB.cpp
- source/Applications/Advanced/Downsample/Downsample.cpp
- source/Applications/Advanced/HandEyeCalibration/PoseConversions/PoseConversions.cpp
- source/Applications/Advanced/HandEyeCalibration/UtilizeEyeInHandCalibration/UtilizeEyeInHandCalibration.cpp
- source/Applications/Basic/FileFormats/ReadIterateZDF/ReadIterateZDF.cpp
- source/Applications/Basic/Visualization/CaptureLiveVis3D/CaptureLiveVis3D.cpp
- source/CMakeLists.txt
- source/Camera/Basic/Capture/Capture.cpp
- source/Camera/Basic/Capture2D/Capture2D.cpp
- source/Camera/Basic/CaptureAssistant/CaptureAssistant.cpp
- source/Camera/Basic/CaptureFromFile/CaptureFromFile.cpp
- source/Camera/Basic/CaptureHDRLoop/CaptureHDRLoop.cpp
- source/Camera/Basic/CaptureTutorial.md
- source/Camera/Basic/QuickCaptureTutorial.md
- source/Camera/InfoUtilOther/GetCameraIntrinsics/GetCameraIntrinsics.cpp
- source/Camera/InfoUtilOther/ZividBenchmark/ZividBenchmark.cpp
We've agreed to stop duplicating sample data in each repository. Instead we will host all sample data on webpage/downloads/ZividSampleData.zip.
> Move files to zivid data

- continuous-integration/linux/build.sh
As of Zivid 2.0 we don't need to skip clang on Ubuntu 16.04. Also remove an outdated TODO.
> Dont skip clang

- source/Camera/Basic/CaptureHDRCompleteSettings/CaptureHDRCompleteSettings.cpp
Support for bidirectional patterns is dropped in Zivid 2.0.0
> Remove bidirectional patterns

- README.md
- source/Applications/Advanced/HandEyeCalibration/UtilizeEyeInHandCalibration/UtilizeEyeInHandCalibration.cpp
Update UtilizeEyeInHandCalibration sample to let the user choose between transforming a single data point or the entire point cloud.
> Update utilize eye in hand sample

- source/Applications/Advanced/HandEyeCalibration/README.md
Fixed these two issues:
Absolute URLs in readme - https://github.com/zivid/zivid-cpp-samples/issues/116
Bad links in readme - https://github.com/zivid/zivid-cpp-samples/issues/133
> Fix bad URLs in HandEyeCalibration readme

- source/Applications/Advanced/CaptureUndistortRGB/CaptureUndistortRGB.cpp
- source/Applications/Advanced/CreateDepthMap/CreateDepthMap.cpp
- source/Applications/Advanced/Downsample/Downsample.cpp
- source/Applications/Advanced/HandEyeCalibration/HandEyeCalibration/HandEyeCalibration.cpp
- source/Applications/Advanced/HandEyeCalibration/PoseConversions/PoseConversions.cpp
- source/Applications/Advanced/HandEyeCalibration/UtilizeEyeInHandCalibration/UtilizeEyeInHandCalibration.cpp
- source/Applications/Advanced/MultiCamera/MultiCameraCalibration/MultiCameraCalibration.cpp
- source/Applications/Advanced/MultiCamera/MultiCameraCalibrationFromZDF/MultiCameraCalibrationFromZDF.cpp
- source/Applications/Advanced/MultiCamera/StitchByTransformation/StitchByTransformation.cpp
- source/Applications/Advanced/MultiCamera/StitchByTransformationFromZDF/StitchByTransformationFromZDF.cpp
- source/Applications/Basic/FileFormats/ReadIterateZDF/ReadIterateZDF.cpp
- source/Applications/Basic/Visualization/CaptureFromFileCameraVis3D/CaptureFromFileCameraVis3D.cpp
- source/Applications/Basic/Visualization/CaptureVis3D/CaptureVis3D.cpp
- source/Applications/Basic/Visualization/CaptureWritePCLVis3D/CaptureWritePCLVis3D.cpp
- source/Applications/Basic/Visualization/ReadPCLVis3D/ReadPCLVis3D.cpp
- source/Camera/Advanced/CaptureHDRLoop/CaptureHDRLoop.cpp
- source/Camera/Basic/Capture/Capture.cpp
- source/Camera/Basic/Capture2D/Capture2D.cpp
- source/Camera/Basic/CaptureAssistant/CaptureAssistant.cpp
- source/Camera/Basic/CaptureFromFileCamera/CaptureFromFileCamera.cpp
- source/Camera/Basic/CaptureHDR/CaptureHDR.cpp
- source/Camera/Basic/CaptureHDRCompleteSettings/CaptureHDRCompleteSettings.cpp
- source/Camera/Basic/CaptureWithSettingsFromYML/CaptureWithSettingsFromYML.cpp
- source/Camera/InfoUtilOther/CameraUserData/CameraUserData.cpp
- source/Camera/InfoUtilOther/FirmwareUpdater/FirmwareUpdater.cpp
- source/Camera/InfoUtilOther/GetCameraIntrinsics/GetCameraIntrinsics.cpp
- source/Camera/InfoUtilOther/ZividBenchmark/ZividBenchmark.cpp
Change exception handling to always return EXIT_FAILURE, when handling exception. 
Before EXIT_FAILURE was only returned if one enters '\n' after an exception catch
> Remove the need to enter \n to return EXIT_FAILURE

- README.md
- source/CMakeLists.txt
- source/Camera/Maintenance/CorrectCameraInField/CorrectCameraInField.cpp
- source/Camera/Maintenance/VerifyCameraInField/VerifyCameraInField.cpp
This commit adds the following two samples:
- VerifyCameraTrueness
- CorrectCameraTrueness
Their purpose is to demonstrate the most important parts of the
experimental "in-field correction" API introduced in SDK 2.2.
> Add samples showing in-field verification and correction

- README.md
- source/Camera/Basic/CaptureHDRCompleteSettings/CaptureHDRCompleteSettings.cpp
Add engine to the list of settings in captureHDRCompleteSettings. 
Add line in sample discription that engine setting requires SDK v2.2 or newer
> Add Engine to list of settings

- source/Applications/Advanced/HandEyeCalibration/HandEyeCalibration/HandEyeCalibration.cpp
Modified handeyecalibration sample to let user input eih or eth for calibration eye-in-hand or eye-to-hand
> Add possibility to choose between eye in hand or object in hand

- README.md
- source/Camera/Advanced/CaptureHDRLoop/CaptureHDRLoop.cpp
- source/Camera/Basic/CaptureHDR/CaptureHDR.cpp
- source/Camera/Basic/CaptureHDRCompleteSettings/CaptureHDRCompleteSettings.cpp
- source/Camera/Basic/CaptureWithSettingsFromYML/CaptureWithSettingsFromYML.cpp
Add logic to check if Zivid One or Zivid Two is connected and use settings
accordingly.
This commit requires an update of SAMPLE_DATA to run the samples that
read settings from file.
> Use settings based on which camera is connected

- source/Applications/Basic/Visualization/ReadPCLVis3D/ReadPCLVis3D.cpp
Updated sample to use .pcd from SampleData instead of your own point cloud. This makes the sample independent of CaptureWritePCLVis3D.
> Modify ReadPCLVis3D sample to use .pcd from SampleData
